#!/bin/sh

# Get the latest changes from the main repository
git fetch origin

# Checkout the main branch (or any other branch you want to track)
git checkout main

# Update submodules to the latest commit
git submodule update --init --recursive

# Push the updated submodules to their respective repositories
for submodule in $(git submodule | cut -d' ' -f2); do
  cd $submodule
  git add .
  git commit -m "Update submodule $submodule"
  git push origin main
  cd ..
done