version: "3"

services:
  namenode-zeppelin:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode-zeppelin
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
    volumes:
      - hadoop_namenode-zeppelin:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode-zeppelin:8020
    ports:
      - "9870:9870"
      - "9000:9000"
    healthcheck:
      interval: 5s
      retries: 100

  datanode-zeppelin:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-zeppelin
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
    volumes:
      - hadoop_datanode-zeppelin:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode-zeppelin:8020
    depends_on:
      namenode-zeppelin:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100

  spark-master-zeppelin:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master-zeppelin
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode-zeppelin:8020
      - SPARK_HOME=/opt/zeppelin/interpreter
    depends_on:
      namenode-zeppelin:
        condition: service_healthy
      datanode-zeppelin:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker-zeppelin:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-zeppelin
    environment:
      - SPARK_MASTER=spark://spark-master-zeppelin:7077
    depends_on:
      spark-master-zeppelin:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100
    ports:
      - "8081:8081"

  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "9090:1234"
    volumes:
      - ./notebook:/opt/zeppelin/notebook
      - ./data:/opt/zeppelin/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode-zeppelin:8020
      - SPARK_MASTER=spark://spark-master-zeppelin:7077
      - ZEPPELIN_NOTEBOOK_DIR=/opt/zeppelin/notebook
      - SPARK_HOME=/opt/zeppelin/interpreter
    depends_on:
      spark-master-zeppelin:
        condition: service_healthy
      namenode-zeppelin:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100

volumes:
  hadoop_namenode-zeppelin:
  hadoop_datanode-zeppelin:

